### ISSUE TITLE
Default implementations for new Invocation.Builder methods

### ISSUE THREAD

**Issue by mattnelson** [jax-rs/api#561]
Since the java target has been raised to 1.8 default method implementation can be supplied when an interface is changed. I pulled down the latest milestone and had to implement two new `rx ` methods on the `Invocation.Builder`. Would it be possible to have default implementations that throw UnsupportedOperationException?

https://github.com/jax-rs/api/blob/2.1-m09/jaxrs-api/src/main/java/javax/ws/rs/client/Invocation.java#L290-L312

**Comment by pavelbucek** [comment]
What message would that convey? Are you implying that the JAX-RS implementation wouldn't be required to implement those methods?

**Comment by mattnelson** [comment]
> What message would that convey? Are you implying that the JAX-RS implementation wouldn't be required to implement those methods?

I guess that is root of my question. Should the specification take advantage of the new language features that allow the interface to change passively? Or should default methods be avoided unless there is actually a "real" default implementation?

**Comment by andymc12** [comment]
Hi Matt,

In this case, we want all vendors/implementors to implement the new rx()
methods.  Otherwise we could have portability problems (i.e. a user moves
their app from one vendor to another and now rx() is broken).

In other cases, the JAX-RS 2.1 spec does make use of the new default
implementation feature.  For example, some methods in the MessageBodyReader
and MessageBodyWriter interfaces are no longer necessary for users to
implement, so in 2.1, they are default methods, allowing the user to write
less code.

Hope this helps,

Andy

**Comment by mattnelson** [comment]
Thanks for the clarification.
